export const Users = [
    {
      id:1,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA3LG39N50LKQDKeXCChIamU9qRYl-lMWTAsKa_h8tKTofkCJ8LPQ00bwfTz2kEOebOf4&usqp=CAU",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLhiY0yX0xbz6qdtq7joRNwnJtisbRnFbFHmqlUuUuwfmKn4ilXkWhnhVdKXoSiylmzao&usqp=CAU",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://best4geeks.com/wp-content/uploads/2018/07/65-stylish-profile-pic-1.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://alleducationresult.com/wp-content/uploads/2023/03/sdfds.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://i.pinimg.com/originals/0d/23/9e/0d239e3a38bacf7af6739a94d9b8d289.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBmEFZDlxAuOtJc3Q6EkW8wju5bmeKWa9NdKuB26sgOCekcG4pU1EvcRHL4ElstOlorKI&usqp=CAU",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0FbNf3tnYKvlCovzxnKtNwjrMoK38KcnzCbB79HSTjCPbD0dhEszQEColIa2bKkz5LPc&usqp=CAU",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://www.broomstickwed.com/wp-content/uploads/2022/05/sexy-russian-woman-450x501.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://i.pinimg.com/736x/43/37/33/433733b1ab647e3c80796f0efc568f09.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://i.ytimg.com/vi/ciaJIwmw22k/maxresdefault.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://nriol.com/images/fort4.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://hips.hearstapps.com/hmg-prod/images/cute-baby-animals-1558535060.jpg?crop=1.00xw:0.669xh;0,0.158xh&resize=1200:*",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://st2.depositphotos.com/2403851/5450/i/450/depositphotos_54507683-stock-photo-cute-little-duckling.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://thumbs.dreamstime.com/b/orange-fruit-fresh-cutting-slicing-image-background-52381569.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?cs=srgb&dl=pexels-pixabay-51312.jpg&fm=jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://media.istockphoto.com/id/481750586/photo/masala-sin.jpg?s=612x612&w=0&k=20&c=0KmrVCmb6AuMv9O41E-8tU2WD6DVyVcVxin4DXhzx_c=",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://www.justwords.in/wp-content/uploads/2020/10/indian-food-image.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://thepointsguy.global.ssl.fastly.net/us/originals/2019/03/delta-wing-airplane-view-mountains-window-landscape.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://www.travelandleisure.com/thmb/Om3sth4C6kRWrs2tdci3H0CnuH8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/gallery-uffizi-florence-italy-ONLINEMUSE0320-7c5f3904408c4c8aabd2f15cd6d47a4b.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?cs=srgb&dl=pexels-chan-walrus-958545.jpg&fm=jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  
